### ISSUE TITLE
Dataset Augment: Add PCA / NMF / etc.

### ISSUE THREAD

**Issue by pcingola** [AstraZeneca-NGS/LogMl#54]
```
dataset_augment:
  enable: true
  ...
  # Add PCA componenets based on some variables (matched by regex)
  # Format:
  #    name:
  #        number: 10
  #        variables: ['*_DNA']
  pca: 
    dna_mutataions:
        number: 10
        variables: ['*_DNA']
    log2_ratio:
        number: 5
        variables: ['.*_LOG2', 'log2_.*']
    clinical:
        number: 3
        variables: ['sex', 'age', 'smoker', 'tumor_type']
```
